#! /bin/bash
echo "#Prueba que la app compile"
echo "#Prueban los codigos unitarios"
echo "#Test de analisis de codigo"
echo "#Genera binarios"
echo "#Descarga imagen de Docker linux ubuntu"
echo "#Instalando JAVA 11"
echo "#Descarga imagen de Docker mysql"
echo "#Crea base de datos via imagen de docker"
echo "#Carga Script en base de datos"
echo "#Carga Script en base de datos"
echo "#Configura el sistema"
echo "#Sespliega el sistema en un ambiente de pruebas"
echo "#Realiza Pruebas de regression"
echo "#Realiza Pruebas de aceptacion"
echo "#Realiza Pruebas de capacidad"
echo "#Realiza Pruebas de seguridad"
echo "#Se despliega en produccion"
